//PRODUCTS
export const TYPES_PRODUCTS = {
  GET_PRODUCTS: "GET_PRODUCTS",
};

//CART
export const TYPES_CART = {
  ADD_T0_CART: "ADD_T0_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL: "REMOVE_ALL",
};
